# permissions for end users to view fetchdata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fetchdata-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: curator
    app.kubernetes.io/part-of: curator
    app.kubernetes.io/managed-by: kustomize
  name: fetchdata-viewer-role
rules:
- apiGroups:
  - curator.curator
  resources:
  - fetchdata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - curator.curator
  resources:
  - fetchdata/status
  verbs:
  - get
