# permissions for end users to edit reportapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: reportapi-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: curator
    app.kubernetes.io/part-of: curator
    app.kubernetes.io/managed-by: kustomize
  name: reportapi-editor-role
rules:
- apiGroups:
  - curator.curator
  resources:
  - reportapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - curator.curator
  resources:
  - reportapis/status
  verbs:
  - get
