apiVersion: curator.curator/v1alpha1
kind: FetchData
metadata:
  labels:
    app.kubernetes.io/name: fetchdata
    app.kubernetes.io/instance: fetchdata-sample
    app.kubernetes.io/part-of: curator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: curator
  name: fetchdata-sample
spec:
  # TODO(user): Add fields here
