apiVersion: curator.curator/v1alpha1
kind: CuratorConfig
metadata:
  labels:
    app.kubernetes.io/name: curatorconfig
    app.kubernetes.io/instance: curatorconfig-sample
    app.kubernetes.io/part-of: curator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: curator
  name: curatorconfig-sample
spec:
  # TODO(user): Add fields here
