name: publish

on:
  push:
    branches:
      - main

  registry_package:
    types:
      - published
    name:
      - ghcr.io/dystewart/curator-manager:latest

  workflow_dispatch:

jobs:
  publish-vault-k8s-login:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUBLISH_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push the Docker image
        run: |
          docker build -t ghcr.io/dystewart/curator-manager:latest .
          docker push ghcr.io/dystewart/curator-manager:latest
