name: Push manager to curator/curator-test

on:
  push:
    branches:
      - testing


env:
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  IMAGE: curator-test
  TAG:   latest
  REPO:  curator

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build and push 
        run: |
          docker login -u ${{ env.QUAY_USERNAME }} -p ${{ env.QUAY_PASSWORD }} quay.io
          make docker-build IMG=quay.io/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }}
          make docker-push  IMG=quay.io/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }}
