name: Push manager to curator/curator-test

on:
  push:
    branches:
      - testing


env:
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  IMAGE: curator-test
  TAG:   latest
  REPO:  curator

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Quay Login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ env.QUAY_USERNAME }}
          password: ${{ env.QUAY_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/${{ env.REPO }}/${{ env.IMAGE }}:${{ env.TAG }}
          context: .
